---
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
#AntiCheat main configuration file!
#Current version: 2.5.3
#What should be blocked?
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
#true = ENABLE
#false = DISABLE
#log = Console info logging
#kick = Player kick
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
   Plugin-Version: 2.5.3
   Config-Version: 3.1.8
#---------------NoKnockBack---------------#
#Do you want to enable NoKnockBack Detection?

   NoKnockBack: true

#How much KnockBack must a player take to be legit?
#Increase this to 1.3 if NoKnockBack is not detected.
#Decrease this to 0.3 if NoKnockBack is causing false
#positives. Standard: 0.4
#NEVER set this higher than 1.4

   MinKnockBack: 0.4

#Which punishment should take place?

   NoKnockBack-Punishment: kick

#Which Message Should be shown if NoKnockBack is detected?

   NoKnockBack-Message: "[AntiCheat] > NoKnockBack is not allowed!"

#-----------------OneHit------------------#
#Do you want to stop Players from dealing more than 19.9
#damage to prevent OneHit kills?

   OneHit: false

#Which Punishment should take place?

   OneHit-Punishment: kick

#Which Message Sould be shown if OneHit is detected?

   OneHit-Message: "[AntiCheat] > OneHit is not allowed!"

#---------------Unkillable----------------#
#Do you want to enable Unkillable Detection?

   Unkillable: true

#How much Damage must a player take to be legit?
#Increase this to 1 if Unkillable is not detected.
#Decrease this to 0.001 if Unkillable is causing false
#positives. Standard: 0.1
#NEVER set this higher than 1

   MinDamage: 0.1

#Wich Punishment should take place?

   Unkillable-Punishment: kick

#Wich Message Sould be shown if Unkillable is detected?

   Unkillable-Message: "[AntiCheat] > Unkillable is not allowed!"

#----------------KillAura-----------------#
#Do you want to enable advanced KillAura angle check?

   KillAura: true

#Wich Punishment should take place?

   KillAura-Punishment: kick

#Wich Message Sould be shown if KillAura is detected?

   KillAura-Message: "[AntiCheat] > KillAura is not allowed!"

#-----------------Reach-------------------#
#Do you want to enable Reach check?

   Reach: true

#How much Range may a player have to be legit?
#Decrease this to 3.8 if Reach is not detected.
#Increase this to 4 if Reach is causing false
#positives. Standard: 3.9
#NEVER set this lower than 3.8

   MaxRange: 3.9

#Wich Punishment should take place?

   Reach-Punishment: kick

#Wich Message Sould be shown if Reach is detected?

   Reach-Message: "[AntiCheat] > Reach is not allowed!"

#----------------ForceOP------------------#
#Do you want to enable advanced ForceOP check?
#READ AntiForceOP.txt BEFORE ENABLING!

   ForceOP: false

#-----------------NoClip------------------#
#Do you want to enable NoClip Detection?
#This prevents players form glitching though blocks.
#This is still W.I.P and may cause false positives.
#Disable this if you want.
#If this caueses crashes, please report it to the Author!

   NoClip: true

#Which Punishment should take place?

   NoClip-Punishment: log

#Which Message Should be shown if NoClip is detected?

   NoClip-Message: "[AntiCheat] > NoClip is not allowed!"

#//////////////////////////////////////////////////////
#//                                                  //
#//     AntiCheat by DarkWav.                        //
#//     Distributed under the ImagicalMine License.  //
#//     Do not redistribute in modified form!        //
#//     All rights reserved.                         //
#//                                                  //
#//////////////////////////////////////////////////////
...
