name: AntiCheat
main: DarkWav\AntiCheat
version: 1.4 (b2)
author: DarkWav (Darku)
api: [1.14.0, 2.0.0]
commands:
      anticheat:
           description: AnitCheat main command
           aliases: ["AntiCheat"]
permissions:
    anticheat:
        default: op
        description: "Allows to use all AntiCheat features."
children:
    anticheat.bypass:
        default: op
        description: "Allows to bypass AntiCheat."