name: AntiCheat
main: DarkWav\AntiCheat\AntiCheat
version: 2.2.0
load: STARTUP
enable: STARTUP
author: DarkWav (Darku)
api: ["3.0.0","2.1.0","2.0.0","1.14.0","1.13.2","1.0.0"]
commands:
      anticheat:
           description: Shows AntiCheat version
           aliases: ["AntiCheat"]
      ac:
           description: Shows AntiCheat version
           aliases: ["AntiCheat"]
permissions:
    anticheat:
        description: "Allows to use all AntiCheat features."
children:
    anticheat.bypass:
        default: op
        description: "Allows to bypass AntiForceGameMode."
    anticheat.op:
        description: "A permission."
