name: AntiCheat
main: DarkWav\AntiCheat
version: 2.3.1
load: STARTUP
author: DarkWav (Darku)
api: ["2.1.0","2.0.0","1.14.0","1.13.2","1.0.0"]
commands:
      anticheat:
           description: AntiCheat main command
           aliases: ["AntiCheat"]
      ac:
           description: AntiCheat main command
           aliases: ["AntiCheat"]