---
#AntiCheat main configuration file
#What should be blocked?
#Do you want to enable AntiKnockBack Detection?

   NoKnockBack: true

#How much KnockBack must a player take to be legit?
#Increase this to 1.3 if NoKnockBack is not detected.
#Decrease this to 0.39 if NoKnockBack is causing false
#positives. Standard: 0.4
#NEVER set this higher than 1.4

   MinKnockBack: 0.4

#Do you want to stop Players from dealing more than 19.9
#damage to prevent OneHit kills?

   OneHit: false

#Do you want to enable Unkillable Detection?

   Unkillable: true

#How much Damage must a player take to be legit?
#Increase this to 1 if Unkillable is not detected.
#Decrease this to 0.001 if Unkillable is causing false
#positives. Standard: 0.1
#NEVER set this higher than 1.1

   MinDamage: 0.1

#Do you want to enable advanced KillAura angle check?

   KillAura: true

#Do you want to enable advanced ForceOP check?
#READ AntiForceOP.txt BEFORE ENABLING!

   ForceOP: false
   
#Do you want to enable WallHack check?

   WallHack: true

#AntiCheat main configuration file end
...
