---
#AntiCheat main configuration file
#Wich Cheats should be blocked?
   Unkillable: true
   OneHit: true
   AntiKnockBack: true
   ForceField: true
   ForceGameMode: true
#Speed is NOT oficially supported currently,
#Bad rewiws for that Speed doesn´t work won´t be tolerated! #Use Speed at your own risk!
   Speed: false
#AntiCheat main configuration file end
...
