---
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
#AntiCheat main configuration file.
#Current version: 2.6.1
#What should be blocked?
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
#true = ENABLE
#false = DISABLE
#block = block Hack
#kick = Player kick
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
   Plugin-Version: 2.6.2
   Config-Version: 3.3.2
#Enables i am waching you message
   I-AM-WATCHING-YOU: true
#---------------NoKnockBack---------------#
#Do you want to enable NoKnockBack Detection?

   NoKnockBack: true

#How much KnockBack must a player take to be legit?
#Increase this to 1.3 if NoKnockBack is not detected.
#Decrease this to 0.3 if NoKnockBack is causing false
#positives. Standard: 0.4
#NEVER set this higher than 1.4

   MinKnockBack: 0.4

#Which Message Should be shown if NoKnockBack is detected?

   NoKnockBack-Message: "[AntiCheat] > NoKnockBack is not allowed!"

#---------------BadEnchants---------------#
#Do you want to stop Players from dealing more than 19.9
#damage to prevent OneHit kills?

   OneHit: false

#Which Punishment should take place?

   OneHit-Punishment: kick

#Which Message Sould be shown if OneHit is detected?

   OneHit-Message: "[AntiCheat] > OneHit is not allowed!"

#Do you want to enable Unkillable Detection?

   Unkillable: true

#How much Damage must a player take to be legit?
#Increase this to 1 if Unkillable is not detected.
#Decrease this to 0.001 if Unkillable is causing false
#positives. Standard: 0.1
#NEVER set this higher than 1

   MinDamage: 0.1

#Wich Message Sould be shown if Unkillable is detected?

   Unkillable-Message: "[AntiCheat] > Unkillable is not allowed!"

#----------------Fly/Glide----------------#
#Do you want to enable Fly and Glide check?
#This should block Spider, Jesus and HighJump as well...
#This wont have any problems with falling or jumping,
#even if the player has JumpBoost 2.

   Fly: true

#How many moves may a player be flying before detection?
#20 Should work fine. (Standard)
#NEVER set this lower than 10
#Increase if Fly causes false poitives.

   Fly-Threshold: 20

#Wich Punishment should take place if Fly is detected?

   Fly-Punishment: kick

#Wich Message Sould be shown if Fly is detected?

   Fly-Message: "[AntiCheat] > Fly is not allowed!"

#Wich Punishment should take place if Glide is detected?

   Glide-Punishment: kick

#Wich Message Sould be shown if Fly is detected?

   Glide-Message: "[AntiCheat] > Glide is not allowed!"

#-----------------Speed-------------------#
#Do you want to enable Speed check?
#This works with falling.

   Speed: true

#Wich Punishment should take place?

   Speed-Punishment: kick

#How many times must a player be hacking before detection?
#5 Should work fine. (Standard)
#NEVER set this to 0

   Speed-Threshold: 5

#Wich Message Sould be shown if Spider is detected?

   Speed-Message: "[AntiCheat] > Speed is not allowed!"

#-----------------Reach-------------------#
#Do you want to enable Reach check?

   Reach: true

#How much Range may a player have to be legit?
#Decrease this to 3.8 if Reach is not detected.
#Increase this to 4 if Reach is causing false
#positives. Standard: 3.9
#NEVER set this lower than 3.8

   MaxRange: 3.9

#Wich Punishment should take place?

   Reach-Punishment: kick

#Wich Message Sould be shown if Reach is detected?

   Reach-Message: "[AntiCheat] > Reach is not allowed!"

#----------------ForceOP------------------#
#Do you want to enable advanced ForceOP check?
#READ AntiForceOP.txt BEFORE ENABLING!

   ForceOP: false

#-----------------NoClip------------------#
#Do you want to enable NoClip Detection?
#This prevents players form glitching though blocks.
#This is still W.I.P and may cause false positives.
#Disable this if you want.
#If this caueses crashes, please report it to the Author!

   NoClip: true

#Which Punishment should take place?

   NoClip-Punishment: block

#Which Message Should be shown if NoClip is detected?

   NoClip-Message: "[AntiCheat] > NoClip is not allowed!"

#//////////////////////////////////////////////////////
#//                                                  //
#//     AntiCheat by DarkWav.                        //
#//     Distributed under the ImagicalMine License.  //
#//     Do not redistribute in modified form!        //
#//     All rights reserved.                         //
#//                                                  //
#//////////////////////////////////////////////////////
...
