---
#AntiCheat main configuration file
#What should be blocked?
#Do you want to enable NoKnockBack Detection?

   NoKnockBack: true

#How much KnockBack must a player take to be legit?
#Increase this to 1.3 if NoKnockBack is not detected.
#Decrease this to 0.39 if NoKnockBack is causing false
#positives. Standard: 0.4
#NEVER set this higher than 1.3

   MinKnockBack: 0.4

#Wich Punishment should take place?

   NoKnockBack-Punishment: kick

#Wich Message Sould be shown if NoKnockBack is detected?

   NoKnockBack-Message: "[AntiCheat] > NoKnockBack is not allowed!"

#Do you want to stop Players from dealing more than 19.9
#damage to prevent OneHit kills?

   OneHit: false

#Wich Punishment should take place?

   OneHit-Punishment: kick

#Wich Message Sould be shown if OneHit is detected?

   OneHit-Message: "[AntiCheat] > OneHit is not allowed!"

#Do you want to enable Unkillable Detection?

   Unkillable: true

#How much Damage must a player take to be legit?
#Increase this to 1 if Unkillable is not detected.
#Decrease this to 0.001 if Unkillable is causing false
#positives. Standard: 0.1
#NEVER set this higher than 1

   MinDamage: 0.1

#Wich Punishment should take place?

   Unkillable-Punishment: kick

#Wich Message Sould be shown if Unkillable is detected?

   Unkillable-Message: "[AntiCheat] > Unkillable is not allowed!"

#Do you want to enable advanced KillAura angle check?

   KillAura: true

#Wich Punishment should take place?

   KillAura-Punishment: kick

#Wich Message Sould be shown if KillAura is detected?

   KillAura-Message: "[AntiCheat] > KillAura is not allowed!"

#How long can a player Reach to still be legit?
#Decrease this to 3.8 if KillAura is not detected.
#Increase this to 4 if KillAura is causing false
#positives. Standard: 3.9
#NEVER set this lower than 3.8

   MaxRange: 3.9

#Do you want to enable advanced ForceOP check?
#READ AntiForceOP.txt BEFORE ENABLING!

   ForceOP: false

#Do you want to enable NoClip Detection?
#This only allows players to be in the air.
#Causes a Kick if the player is inside of Blocks.
#I DON`T GUARANTEE NO FALSE POSITIVES WITH THIS!
#Disable this instantly if SafeMode is causing
#false positives and report it to the Author!

   NoClip: true

#Do you Want to enable SafeMode to prevent false
#positvises with cobweb, grass, ect?
#HIGHLY recommanded to be kept at "true"

   NoClipSafeMode: true

#Wich Punishment should take place?

   NoClip-Punishment: log

#Wich Message Sould be shown if NoClip is detected?

   NoClip-Message: "[AntiCheat] > NoClip is not allowed!"

#AntiCheat main configuration file end
...
