---
#AntiCheat main configuration file
#Wich Cheats should be blocked?
   AntiKnockBack: true
   OneHit: true
   Unkillable: true
   ForceField: true
   ForceGameMode: true
#Old Detections:
   Speed: false
#AntiCheat main configuration file end
...
