---
#AntiCheat main configuration file
#Wich Cheats should be blocked?
   Unkillable: true
   OneHit: true
   AntiKnockback: true
#If you want Speed Detections, use NoCheatPE
#AntiCheat main configuration file end
...
