---
#AntiCheat main configuration file
#Some functions are Beta, some not
#Release-Detections:
#Wich Checks should be enabled?
   Unkillable: true
   OneHit: true
   Nuker: [Comming Soon]
   ForceOP: [Comming Soon]
#Beta-Detections (Could be Useless and cause lag)
#Do you want to allow Beta Checks?
#NEVR set them true on a production server.
#Wich Beta Checks should be enabled?
   Speed: false
   ForceGameMode: false
#AntiCheat main configuration file end
...
